[web.rest]
host = "localhost"
port = 5443
proxy = "hortalink.dev"

[web.client]
host = "localhost"
proxy = "hortalink.dev"
port = 4321

[web.cdn]
host = "localhost"
port = 5767
storage = "/usr/src/app/storage"
proxy = "cdn.hortalink.dev"

[database]
username = "postgres"
database = "hortalink"
password = "postgres"
host = "localhost"
port = 5432

[secrets.google]
client_id = ""
client_secret = ""

[secrets.facebook]
client_id = ""
client_secret = ""

[secrets.linkedin]
client_id = ""
client_secret = ""

[rabbitmq]
host = "localhost"
port = 5672
username = "rabbit"
password = ""

[websocket]
host = "localhost"
port = 9002
proxy = "gateway.hortalink.dev"