[workspace]
members = [
    "common",
    "core",
    "rest-server",
    "microservices",
    "cdn-server"
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
sqlx = { version = "0.7.3", default-features = false, features = [ "runtime-tokio", "tls-rustls", "postgres", "uuid" ] }
tokio = { version = "1.35.0", default-features = false, features = ["macros", "rt-multi-thread"] }
axum = { version = "0.7.2", default-features = false, features = ["http2", "json", "tokio", "tower-log", "query"] }
redis = { version = "0.24.0", default-features = false, features = ["ahash", "tokio-comp"] }
amqprs = { version = "1.5.1", default-features = false, features = ["tls"] }
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.110" }
log = { version = "0.4.20" }
env_logger = { version = "0.10.1" }
axum-login = { version = "0.12.0" }
tower-sessions = { version = "0.9.1", default-features = false, features = ["postgres-store"] }
