[workspace]
members = [
    "common",
    "core",
    "rest-server",
    "microservices",
    "cdn-server"
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
# https://github.com/launchbadge/sqlx
sqlx = { version = "0.7.3", default-features = false, features = [ "runtime-tokio", "tls-rustls", "postgres", "macros", "uuid" ] }
# https://github.com/tokio-rs/tokio
tokio = { version = "1.35.0", default-features = false, features = ["macros", "rt-multi-thread"] }
# https://github.com/tokio-rs/axum
axum = { version = "0.7.2", default-features = false, features = ["http2", "json", "tokio", "tower-log", "query"] }
# https://github.com/redis-rs/redis-rs
redis = { version = "0.24.0", default-features = false, features = ["ahash", "tokio-comp"] }
# https://github.com/gftea/amqprs
amqprs = { version = "1.5.1", default-features = false, features = ["tls"] }
# https://github.com/serde-rs/serde
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
# https://github.com/rust-lang/log
log = { version = "0.4.20" }
# https://github.com/rust-cli/env_logger
env_logger = { version = "0.10.1" }