version: '3.8'

services:
  nginx:
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./localhost.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rest-server
      - web
      - cdn-server
      - websocket

  rest-server:
    build:
      context: .
      dockerfile: ./rest-server/Dockerfile
    network_mode: host
    volumes:
      - /home/luisf/storage:/usr/src/app/storage
      - /home/luisf/Projects/hortalink/application.toml:/usr/src/app/settings.toml
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    network_mode: host

  cdn-server:
    build:
      context: .
      dockerfile: ./cdn-server/Dockerfile
    volumes:
      - /home/luisf/storage:/usr/src/app/storage
      - /home/luisf/Projects/hortalink/application.toml:/usr/src/app/settings.toml
    network_mode: host

  websocket:
    build:
      context: .
      dockerfile: ./websocket/Dockerfile
    volumes:
      - /home/luisf/Projects/hortalink/application.toml:/usr/src/app/settings.toml
    network_mode: host
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hortalink
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: