[package]
name = "app_core"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common" }

amqprs = { workspace = true, features = ["urispec"] }
sqlx = { workspace = true }
log = { workspace = true }