[package]
name = "rest-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common"}
core = { path = "../core" }

sqlx = { workspace = true }
amqprs = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }