[package]
name = "rest-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common"}
app_core = { path = "../core" }

sqlx = { workspace = true, features = ["migrate"] }
amqprs = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
axum-login = { workspace = true }
tower-sessions = { workspace = true }
tower-sessions-sqlx-store = { workspace = true }

async-trait = { version = "0.1.77" }
password-auth = { version = "1.0.0" }
oauth2 = { version = "4.4.2" }
reqwest = { version = "0.11.23", features = ["json"] }
thiserror = "1.0.56"
tower-http = { version = "0.5.1", default-features = false, features = ["cors"] }
http = "1.0.0"