[package]
name = "rest-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common" }
app_core = { path = "../core" }

sqlx = { workspace = true, features = ["macros", "migrate"] }
garde = { workspace = true, features = ["email", "phone-number"] }
axum_garde = { workspace = true, features = ["json", "query"] }
axum = { workspace = true }
tower-http = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
axum-test = { workspace = true }