[package]
name = "cdn-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common"}

sqlx = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
axum = { workspace = true, features = ["multipart"] }
serde_json = { workspace = true }
tower-http = { workspace = true, features = ["cors", "compression-zstd"] }

image = { version = "0.24.8", default-features = false, features = ["webp", "jpeg", "png"] }
img_hash = { version = "3.2.0" }
http = { version = "1.0.0" }