[package]
name = "cdn-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common" }
app_core = { path = "../core" }

axum = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }

[dev-dependencies]
axum-test = { workspace = true }