[package]
name = "common"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true }
log = { workspace = true }
serde_repr = { workspace = true }

toml = { version = "0.8.8" }
num_enum = { version = "0.7.2" }